# Generated by Django 2.0.1 on 2018-03-18 01:22

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20180316_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Rommel\\Documents\\GitHub\\play\\python\\ecommerce\\static_cdn\\protected_media'), upload_to=products.models.upload_product_file_loc),
        ),
    ]
